apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-fulfillment-worker.fullname" . }}-secret
type: Opaque
stringData:
  DB_USER: {{ .Values.rds.username | quote }}
  DB_PASSWORD: {{ .Values.rds.password | quote }}
