apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmend-portal.api.fullname" . }}
  labels:
    {{- include "alertmend-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
stringData:
  DB_HOST: {{ include "alertmend-portal.db.fullname" . }}
  DB_PORT: {{ .Values.db.service.port | quote }}
  DB_NAME: {{ .Values.db.database | quote }}
  DB_USER: {{ .Values.db.username | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
