apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alertmend-portal.api.fullname" . }}
  labels:
    {{- include "alertmend-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "alertmend-portal.name" . }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "alertmend-portal.name" . }}
        app.kubernetes.io/component: api
        tier: application
    spec:
      {{- if .Values.imageCredentials.enabled }}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.secretName }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4000
          env:
            - name: PORT
              value: "4000"
          envFrom:
            - secretRef:
                name: {{ include "alertmend-portal.api.fullname" . }}
          resources:
{{ toYaml .Values.api.resources | indent 12 }}
          startupProbe:
            httpGet:
              path: /ready
              port: 4000
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 4000
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 10
