apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmend-portal.db.fullname" . }}
  labels:
    {{- include "alertmend-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.db.database | quote }}
  POSTGRES_USER: {{ .Values.db.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.password | quote }}
