apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertmend-portal.db.fullname" . }}
  labels:
    {{- include "alertmend-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "alertmend-portal.name" . }}
    app.kubernetes.io/component: db
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: postgres
      name: postgres
