apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order-catalog-service.fullname" . }}-mongodb
  labels:
    {{- include "order-catalog-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "order-catalog-service.name" . }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "order-catalog-service.name" . }}
        app.kubernetes.io/component: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          ports: [{ name: mongo, containerPort: {{ .Values.mongodb.port }} }]
          volumeMounts:
            - name: data
              mountPath: /data/db
          resources:
{{ toYaml .Values.mongodb.resources | indent 12 }}
          startupProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - 'db.adminCommand({ ping: 1 })'
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 30
          readinessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - 'db.adminCommand({ ping: 1 })'
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - 'db.adminCommand({ ping: 1 })'
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "order-catalog-service.fullname" . }}-mongodb
