apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-catalog-service.fullname" . }}-mongodb
  labels:
    {{- include "order-catalog-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "order-catalog-service.name" . }}
    app.kubernetes.io/component: mongodb
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: mongo
      name: mongo
