apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retail-hub.fullname" . }}-mongodb
  labels:
    {{- include "retail-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.username | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.password | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retail-hub.fullname" . }}-mongodb-app
  labels:
    {{- include "retail-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_URI: {{ include "retail-hub.mongoUri" . | quote }}
  MONGO_DATABASE: {{ .Values.mongodb.database | quote }}
