apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "retail-hub.fullname" . }}-mongodb
  labels:
    {{- include "retail-hub.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.mongodb.storage }}
