apiVersion: v1
kind: Service
metadata:
  name: {{ include "retail-hub.fullname" . }}-mongodb
  labels:
    {{- include "retail-hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  selector:
    app.kubernetes.io/name: {{ include "retail-hub.name" . }}
    app.kubernetes.io/component: mongodb
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: mongo
      name: mongo
