apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "retail-hub.fullname" . }}-mongodb
  labels:
    {{- include "retail-hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "retail-hub.name" . }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "retail-hub.name" . }}
        app.kubernetes.io/component: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          ports: [{ name: mongo, containerPort: {{ .Values.mongodb.port }} }]
          envFrom:
            - secretRef:
                name: {{ include "retail-hub.fullname" . }}-mongodb
          volumeMounts:
            - name: data
              mountPath: /data/db
          resources:
{{ toYaml .Values.mongodb.resources | indent 12 }}
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  mongosh --quiet \
                    -u "$MONGO_INITDB_ROOT_USERNAME" \
                    -p "$MONGO_INITDB_ROOT_PASSWORD" \
                    --authenticationDatabase admin \
                    --eval 'db.adminCommand({ ping: 1 })' >/dev/null
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 30
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  mongosh --quiet \
                    -u "$MONGO_INITDB_ROOT_USERNAME" \
                    -p "$MONGO_INITDB_ROOT_PASSWORD" \
                    --authenticationDatabase admin \
                    --eval 'db.adminCommand({ ping: 1 })' >/dev/null
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  mongosh --quiet \
                    -u "$MONGO_INITDB_ROOT_USERNAME" \
                    -p "$MONGO_INITDB_ROOT_PASSWORD" \
                    --authenticationDatabase admin \
                    --eval 'db.adminCommand({ ping: 1 })' >/dev/null
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "retail-hub.fullname" . }}-mongodb
