apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retail-hub.fullname" . }}-postgres
  labels:
    {{- include "retail-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  PG_HOST: {{ include "retail-hub.fullname" . }}-postgres
  PG_PORT: {{ .Values.postgres.port | quote }}
  PG_DATABASE: {{ .Values.postgres.database | quote }}
  PG_USER: {{ .Values.postgres.username | quote }}
  PG_PASSWORD: {{ .Values.postgres.password | quote }}
