apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retail-hub.fullname" . }}-redis
  labels:
    {{- include "retail-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_URL: {{ include "retail-hub.redisUrl" . | quote }}
