apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-event-ingestion-worker.fullname" . }}-secret
type: Opaque
stringData:
  DB_USER: {{ .Values.rds.username | quote }}
  DB_PASSWORD: {{ .Values.rds.password | quote }}
  ES_USERNAME: {{ .Values.elasticsearch.username | quote }}
  ES_PASSWORD: {{ .Values.elasticsearch.password | quote }}
