apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "checkout-memory-service.fullname" . }}
  labels:
    app: checkout-memory-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: checkout-memory-service
  template:
    metadata:
      labels:
        app: checkout-memory-service
        incident-type: oomkilled
        rca-test: alertmend
    spec:
      {{- if .Values.imageCredentials.enabled }}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.secretName }}
      {{- end }}
      containers:
        - name: checkout-memory-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
{{ toYaml .Values.resources | indent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
