apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order-db-connection-pressure.fullname" . }}
  labels:
    app: {{ include "order-db-connection-pressure.name" . }}
    incident-type: rds-connection-exhaustion
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "order-db-connection-pressure.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "order-db-connection-pressure.name" . }}
        incident-type: rds-connection-exhaustion
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ include "order-db-connection-pressure.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          envFrom:
            - secretRef:
                name: {{ include "order-db-connection-pressure.fullname" . }}-secret

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 20
            periodSeconds: 20

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
