apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-db-connection-pressure.fullname" . }}-secret
type: Opaque
stringData:
  DB_HOST: {{ .Values.env.DB_HOST | quote }}
  DB_PORT: {{ .Values.env.DB_PORT | quote }}
  DB_USER: {{ .Values.env.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.env.DB_PASSWORD | quote }}
  DB_NAME: {{ .Values.env.DB_NAME | quote }}
