apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.culprit.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.culprit.name }}
  ports:
    - port: {{ .Values.culprit.service.port }}
      targetPort: {{ .Values.culprit.service.targetPort }}
      protocol: TCP
